import type { Metadata } from "next";
import { Encode_Sans_Semi_Condensed } from "next/font/google";
import { Toaster } from "react-hot-toast";

import "./globals.css";

const encodeSans = Encode_Sans_Semi_Condensed({
  weight: ["400"], // Regular
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${encodeSans.className} antialiased`}>
        {children} <Toaster position="top-right" reverseOrder={false} />
      </body>
    </html>
  );
}
